# Generated by Django 4.2.29 on 2026-03-23 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instalacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activitat", models.CharField(max_length=200)),
                ("inici", models.DateTimeField()),
                ("final", models.DateTimeField()),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("pendent", "Pendent"),
                            ("aprovat", "Aprovat"),
                            ("rebutjat", "Rebutjat"),
                        ],
                        default="pendent",
                        max_length=10,
                    ),
                ),
                (
                    "entitat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instalacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservescorbera.instalacio",
                    ),
                ),
            ],
        ),
    ]
