# Generated by Django 4.2.29 on 2026-04-15 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservescorbera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacio",
            name="color",
            field=models.CharField(default="#d4af37", max_length=7),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="hora_obertura",
            field=models.TimeField(default="08:00"),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="hora_tancament",
            field=models.TimeField(default="23:00"),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="imatge",
            field=models.ImageField(blank=True, null=True, upload_to="instalacions/"),
        ),
        migrations.AddField(
            model_name="reserva",
            name="creat_el",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reserva",
            name="estat",
            field=models.CharField(
                choices=[
                    ("pendent", "Pendent"),
                    ("validada", "Validada"),
                    ("rebutjada", "Rebutjada"),
                ],
                default="pendent",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="instalacio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserves",
                to="reservescorbera.instalacio",
            ),
        ),
    ]
