# Generated by Django 4.2.29 on 2026-05-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservescorbera", "0002_instalacio_color_instalacio_hora_obertura_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia_setmana", models.IntegerField()),
                ("inici", models.TimeField()),
                ("final", models.TimeField()),
                ("activitat", models.CharField(max_length=200)),
                (
                    "entitat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instalacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservescorbera.instalacio",
                    ),
                ),
            ],
        ),
    ]
