# Generated by Django 4.2.29 on 2026-05-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservescorbera", "0003_plantillareserva"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantillareserva",
            old_name="entitat",
            new_name="user",
        ),
    ]
