# Generated by Django 4.2.29 on 2026-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservescorbera", "0004_rename_entitat_plantillareserva_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitatExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titol", models.CharField(max_length=200)),
                ("data", models.DateField()),
                ("inici", models.TimeField()),
                ("final", models.TimeField()),
                (
                    "tipus",
                    models.CharField(default="extra", editable=False, max_length=20),
                ),
            ],
        ),
    ]
