# Generated by Django 4.2.29 on 2026-05-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservescorbera", "0005_activitatextra"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacio",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Si aquest és un sub-espai, tria la instal·lació principal (Ex: El Camp de Futbol 11).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_espais",
                to="reservescorbera.instalacio",
            ),
        ),
    ]
