# Generated by Django 4.2.29 on 2026-05-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservescorbera", "0006_instalacio_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacio",
            name="hora_obertura_finde",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="hora_tancament_finde",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="obert_cap_setmana",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="instalacio",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Si aquest és un sub-espai, tria la instal·lació principal.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_espais",
                to="reservescorbera.instalacio",
            ),
        ),
    ]
