# Generated by Django 4.2.29 on 2026-05-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservescorbera", "0007_instalacio_hora_obertura_finde_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instalacio",
            old_name="hora_obertura_finde",
            new_name="hora_obertura_dissabte",
        ),
        migrations.RenameField(
            model_name="instalacio",
            old_name="hora_tancament_finde",
            new_name="hora_obertura_diumenge",
        ),
        migrations.AddField(
            model_name="instalacio",
            name="hora_tancament_dissabte",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="hora_tancament_diumenge",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="obert_dissabte",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instalacio",
            name="obert_diumenge",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="instalacio",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Si aquest és un sub-espai, tria la instal·lació principal (Ex: El Camp de Futbol 11).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_espais",
                to="reservescorbera.instalacio",
            ),
        ),
    ]
